#!/usr/bin/env python3
"""Transform Horner-style FpExt FMA chains into balanced tree-reductions.

Pattern recognized (auto-generated by zirgen):
    FpExt xK   = BASE   + factor_0 * poly_mix[k_0];
    FpExt xK+1 = xK     + factor_1 * poly_mix[k_1];
    FpExt xK+2 = xK+1   + factor_2 * poly_mix[k_2];
    ...
    FpExt xK+N = xK+N-1 + factor_N * poly_mix[k_N];

Critical path depth = N (the chained add). Each iteration's add depends on the
previous, so the GPU's add latency × N stalls the warp.

Rewrite to:
    FpExt _p0 = factor_0 * poly_mix[k_0];
    FpExt _p1 = factor_1 * poly_mix[k_1];
    ...   (all N+1 muls independent — IGC schedules in parallel)
    FpExt _s_a = _p0 + _p1;
    FpExt _s_b = _p2 + _p3;        (parallel)
    FpExt _s_ab = _s_a + _s_b;     (etc.)
    FpExt xK+N = BASE + _s_total;

Critical path depth = log2(N+1) + 1, saving (N - log2(N+1)) add-latencies per chain.

Safety:
  - Only transform chains where intermediate xN's have NO references outside
    the chain in the same function. Detected by lexical scan within the
    function body.
  - Only handle the exact Horner pattern (single factor, single poly_mix index).
  - Math identity holds via commutativity + associativity of FpExt addition.
"""

import os
import re
import sys

# Match a chain head: "  FpExt xK = SOMETHING + FACTOR * poly_mix[N];"
# SOMETHING and FACTOR are simple identifiers (variable names).
HEAD_RE = re.compile(
    r'^(\s*)FpExt x(\d+) = (\S+) \+ (\S+) \* poly_mix\[(\d+)\];\s*$'
)
# Match a chain continuation: must reference the immediately-previous xK-1
TAIL_RE = re.compile(
    r'^(\s*)FpExt x(\d+) = x(\d+) \+ (\S+) \* poly_mix\[(\d+)\];\s*$'
)
# Function header
FN_RE = re.compile(r'^FpExt rv32im_v2_\d+\(size_t cycle.*\) \{\s*$')
# poly_fp entry
POLY_FP_RE = re.compile(r'^FpExt poly_fp\(.*\) \{\s*$')


def is_simple_var(s):
    """Return True if s is a plain identifier (no operators)."""
    return bool(re.match(r'^[a-zA-Z_]\w*$', s))


def transform_function(lines, fn_start, fn_end):
    """
    lines: list of all source lines.
    fn_start, fn_end: line indices [start, end) for this function body.
    Returns a NEW list of lines for this function with chains tree-reduced.
    """
    # Step 1: collect all xN identifier references in the function (lexically).
    # We use word-boundary regex; comment lines are excluded from external-ref
    # counting (they don't affect codegen).
    # The chain's OWN references (xN appears once on its own LHS and possibly
    # once on the next-line RHS) are subtracted later.
    ref_count = {}  # xN integer -> count
    NAME_RE = re.compile(r'\bx(\d+)\b')
    for i in range(fn_start, fn_end):
        line = lines[i]
        if line.lstrip().startswith('//'):
            continue
        for m in NAME_RE.finditer(line):
            xN = int(m.group(1))
            ref_count[xN] = ref_count.get(xN, 0) + 1

    # Step 2: scan for chains.
    # Output is the rewritten line list for this function body.
    out = []
    i = fn_start
    while i < fn_end:
        line = lines[i]
        head_m = HEAD_RE.match(line)
        if not head_m:
            out.append(line)
            i += 1
            continue
        indent, xK_str, base, factor0, k0 = head_m.groups()
        xK = int(xK_str)
        # Need to confirm this is actually a chain head, not a one-line FMA.
        # Look ahead for chain tail referencing xK.
        chain = [(i, xK, factor0, k0)]
        prev_x = xK
        # Skip comment lines while looking for next chain member
        j = i + 1
        while j < fn_end:
            if lines[j].lstrip().startswith('//') or not lines[j].strip():
                # Comment lines or blank lines may interleave — but in practice
                # the codegen puts one comment line per FpExt line. Allow them.
                j += 1
                continue
            tm = TAIL_RE.match(lines[j])
            if not tm:
                break
            _, xKnext_s, xKprev_s, factor_i, k_i = tm.groups()
            xKnext = int(xKnext_s)
            xKprev = int(xKprev_s)
            if xKprev != prev_x:
                break
            chain.append((j, xKnext, factor_i, k_i))
            prev_x = xKnext
            j += 1

        if len(chain) < 4:
            # Not worth transforming (savings minimal for short chains).
            out.append(line)
            i += 1
            continue

        # Step 3: safety check — all INTERMEDIATE xN's (i.e., chain[0..-1])
        # must be referenced exactly TWICE in the function: once on the own LHS
        # of their declaration and once on the RHS of the next chain member.
        # (Comments don't count because they're excluded from ref_count.)
        # Actually each declaration FpExt xN = ... contains 1 occurrence on LHS,
        # and use as base of next adds 1. So intermediate xN should have exactly
        # 2 refs. The CHAIN BASE (`base` from head) and the chain TAIL (last xN)
        # may have any number of references.
        safe = True
        for idx, (_, xN, _, _) in enumerate(chain[:-1]):
            cnt = ref_count.get(xN, 0)
            if cnt != 2:
                safe = False
                break
        # Also the chain head's xK is itself an intermediate (used by chain[1]).
        # The above loop covered it because chain[:-1] includes the head.

        if not safe:
            # Skip transform; emit original line.
            out.append(line)
            i += 1
            continue

        # Step 4: gather all comment lines that ought to be preserved between
        # chain members. We treat them as a single block to put before the
        # transformed output (preserves loc(...) for debugging).
        last_chain_line = chain[-1][0]
        original_block_lines = lines[i:last_chain_line + 1]

        # Step 5: emit transformed code.
        # 5a: declare N+1 partial products _p0, _p1, ..., _pN.
        # Use the chain's first xN as a name suffix to avoid collisions.
        chain_id = chain[0][1]  # the head xN integer
        partial_names = []
        out.append(f'{indent}// [tree-reduce] chain depth={len(chain)} '
                   f'(was x{chain_id}..x{chain[-1][1]} Horner)\n')
        for k, (_, _, factor, pm_idx) in enumerate(chain):
            pname = f'_tr_{chain_id}_p{k}'
            partial_names.append(pname)
            out.append(f'{indent}auto {pname} = {factor} * poly_mix[{pm_idx}];\n')

        # 5b: tree-reduce sums. Balanced binary tree.
        # If N+1 partials, build levels until one remains.
        current = list(partial_names)
        level = 0
        while len(current) > 1:
            nxt = []
            for k in range(0, len(current) - 1, 2):
                sname = f'_tr_{chain_id}_s{level}_{k // 2}'
                out.append(f'{indent}auto {sname} = {current[k]} + {current[k + 1]};\n')
                nxt.append(sname)
            if len(current) % 2 == 1:
                # Odd man out: promote to next level untouched
                nxt.append(current[-1])
            current = nxt
            level += 1
        sum_name = current[0]

        # 5c: final xN = base + sum
        last_xK = chain[-1][1]
        out.append(f'{indent}FpExt x{last_xK} = {base} + {sum_name};\n')

        i = last_chain_line + 1

    return out


def transform_file(in_path, out_path):
    with open(in_path) as f:
        lines = f.readlines()

    # Find function boundaries
    fn_ranges = []  # list of (start, end, fn_name)
    in_fn = False
    fn_start = 0
    depth = 0
    for i, line in enumerate(lines):
        if not in_fn:
            if FN_RE.match(line) or POLY_FP_RE.match(line):
                in_fn = True
                fn_start = i
                depth = 1
        else:
            # naive brace counting that ignores comments — works because the
            # generated code is well-formed and comments are full-line.
            stripped = line.lstrip()
            if stripped.startswith('//'):
                continue
            for ch in line:
                if ch == '{':
                    depth += 1
                elif ch == '}':
                    depth -= 1
                    if depth == 0:
                        fn_ranges.append((fn_start, i + 1))
                        in_fn = False
                        break

    # Transform each function's body
    out_lines = []
    cursor = 0
    transformed_chains = 0
    for fs, fe in fn_ranges:
        # Emit preamble (lines before this fn)
        out_lines.extend(lines[cursor:fs])
        # Transform fn body
        before = len(out_lines)
        new_body = transform_function(lines, fs, fe)
        # Count chains transformed (lines starting with "[tree-reduce]")
        for ln in new_body:
            if '[tree-reduce]' in ln:
                transformed_chains += 1
        out_lines.extend(new_body)
        cursor = fe
    # Tail
    out_lines.extend(lines[cursor:])

    with open(out_path, 'w') as f:
        f.writelines(out_lines)
    return transformed_chains


def main():
    if len(sys.argv) != 3:
        print("Usage: tree_reduce_fma.py <input_dir> <output_dir>", file=sys.stderr)
        sys.exit(2)
    in_dir = sys.argv[1]
    out_dir = sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    total = 0
    for name in os.listdir(in_dir):
        if not name.startswith('rust_poly_fp_') or not name.endswith('.cpp'):
            # Copy through unchanged.
            src = os.path.join(in_dir, name)
            if os.path.isfile(src):
                with open(src, 'rb') as fin, open(os.path.join(out_dir, name), 'wb') as fout:
                    fout.write(fin.read())
            continue
        n = transform_file(os.path.join(in_dir, name), os.path.join(out_dir, name))
        print(f"  {name}: transformed {n} chains", file=sys.stderr)
        total += n
    print(f"Total chains transformed: {total}", file=sys.stderr)


if __name__ == '__main__':
    main()
