#!/usr/bin/env python3
"""Split recursion/poly_fp.cpp into N noinline sub-functions — PoC, NOT
USABLE AS-IS.

## Status (2026-05-22)

**Default OFF in build.rs. Setting RISC0_RECURSION_SPLIT_POLY_FP=1 with
this script as-written produces a kernel that triggers
UR_RESULT_ERROR_DEVICE_LOST at runtime.**

Diagnosis: the script's closure-based re-emission strategy inflates the
output .so from 13 MB to 59.7 MB (4.6×) because each sub-function
re-emits the transitive closure of every external value it references
— and recursion's codegen front-loads ~689 buffer reads referenced
THROUGHOUT the function (median last-use line = 24116 out of 24750).
Most external deps are buffer loads; some are computed Fp values.
The resulting compiled kernel either runs too long (TDR timeout) or
exceeds GPU resource caps.

## Next-iteration strategy (left for future work)

The right design is to mirror rv32im's pattern more carefully:
- Hoist all 689 buffer loads into ONCE in the entry `poly_fp`,
  store them in `Fp x33[N]` and `FpExt x34[M]` scratch arrays
  allocated on the stack (large but inside one function).
- Pass `Fp* x33, FpExt* x34` to each sub-function.
- Sub-functions reference values via `x33[K]` instead of recomputing.

That preserves the "split-for-IGC-compile" benefit while keeping the
total code size bounded (the buffer loads exist exactly once, not
duplicated 10×).

## What this script does (mechanical reference)

`<in_path>` is the original `poly_fp.cpp`.
`<out_dir>` receives `rust_poly_fp_0.cpp` and `rust_poly_fp_1.cpp` (or
more, see --num-files).

- Each sub-function `recursion_v2_K` (K = N-1 down to 0) processes one
  contiguous body region.
- Cuts are picked at SSA def boundaries that minimise the count of FpExt
  values live across the boundary.
- For each sub-function, the SSA closure of every value it references
  is computed via transitive backward walk through the dep graph; defs
  outside the region are re-emitted at the top (with FpExt accumulator
  imports rewritten to `fargK` params and buffer accessors rewritten to
  the sub-function's `argK` names).
- The entry `poly_fp` calls `recursion_v2_<N-1>` with the 5 buffer
  pointers — args[0]=code, args[1]=out, args[2]=data, args[3]=mix,
  args[4]=accum.

Usage (kept for the future iteration):
  python3 split_poly_fp.py <in_path> <out_dir> [--n 10] [--num-files 2]

Bit-exactness in principle: each statement runs in source order modulo
sub-function boundaries; FpExt accumulator values pass through arg
slots; re-emitted buffer loads are literal copies. The actual runtime
fault is operational (TDR / resource), not semantic.
"""

import argparse
import os
import re
import sys

# A leaf SSA def: `  auto xN = ...;` or `  constexpr Fp xN(...);` or `  FpExt xN = ...;` or `  Fp xN(...);`
SSA_DEF_RE = re.compile(r'^  (?:constexpr )?(?:auto|FpExt|Fp)\s+x(\d+)\s*(?:=|\()')
FPEXT_DEF_RE = re.compile(r'^  FpExt\s+x(\d+)\s*=\s*(.+?);')
POLY_FP_DEF_RE = re.compile(r'^FpExt\s+poly_fp\(.*\)\s*\{\s*$')
NS_CLOSE_RE = re.compile(r'^\}\s*//\s*namespace')
XREF_RE = re.compile(r'\bx(\d+)\b')
ARGS_RE = re.compile(r'args\[(\d+)\]')

# Map original args[K] index to sub-function arg name.
# Recursion uses 5 buffers: 0=code, 1=out, 2=data, 3=mix, 4=accum.
ARG_MAP = {0: 'arg0', 1: 'arg1', 2: 'arg2', 3: 'arg3', 4: 'arg4'}
NUM_BUFS = 5

HEADER_TEMPLATE = """\
// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code is automatically generated by split_poly_fp.py — do not edit.

#include "fp.h"
#include "fpext.h"

#include <cstdint>

constexpr size_t kInvRate = 4;

// clang-format off
namespace risc0::circuit::recursion {

"""

NS_CLOSE = """\
} // namespace risc0::circuit::recursion
// clang-format on
"""


def parse_file(path):
    with open(path) as f:
        lines = f.readlines()
    n = len(lines)
    # Find `FpExt poly_fp(...) {`
    def_open = next(i for i, ln in enumerate(lines) if POLY_FP_DEF_RE.match(ln))
    # Find `size_t mask = steps - 1;` (end of header)
    mask_idx = next(i for i in range(def_open, n) if 'size_t mask' in lines[i])
    header_end = mask_idx + 1
    # Prologue: contiguous `constexpr Fp xN(...);` (and `// loc()` comments).
    p = header_end
    while p < n:
        s = lines[p].strip()
        if s.startswith('//') or s.startswith('constexpr'):
            p += 1
            continue
        break
    prologue_end = p
    # Trailer: walk back from EOF for `} // namespace` line.
    t_idx = next(i for i in range(n - 1, -1, -1) if NS_CLOSE_RE.match(lines[i]))
    # body_end (exclusive) = the `}` closing poly_fp (last non-blank line before t_idx)
    bend = t_idx - 1
    while bend > 0 and lines[bend].strip() == '':
        bend -= 1
    # Now lines[bend] is the `}`. body ends just before it.
    body_end = bend
    return {
        'lines': lines,
        'header_end': header_end,
        'prologue_end': prologue_end,
        'body_start': prologue_end,
        'body_end': body_end,
    }


def build_ssa_table(lines, body_start, body_end):
    """For each defined xN in [body_start, body_end):
       def_line, type, deps (set), last_use_line."""
    table = {}
    last_use = {}
    for li in range(body_start, body_end):
        ln = lines[li]
        m = SSA_DEF_RE.match(ln)
        if not m:
            continue
        xid = int(m.group(1))
        if ln.startswith('  FpExt'):
            t = 'FpExt'
        elif ln.startswith('  auto'):
            t = 'auto'
        else:
            t = 'Fp'
        eq = ln.find('=')
        rhs = ln[eq + 1:] if eq >= 0 else ln
        deps = {int(m2.group(1)) for m2 in XREF_RE.finditer(rhs) if int(m2.group(1)) != xid}
        table[xid] = {'def_line': li, 'type': t, 'deps': deps}
    # Second pass: last_use
    for li in range(body_start, body_end):
        ln = lines[li]
        eq = ln.find('=')
        rhs = ln[eq + 1:] if eq >= 0 else ln
        for m in XREF_RE.finditer(rhs):
            uid = int(m.group(1))
            if uid in table:
                last_use[uid] = li
    for xid, info in table.items():
        info['last_use_line'] = last_use.get(xid, info['def_line'])
    return table


def pick_cuts(table, body_start, body_end, n_funcs, window=200):
    """Pick N-1 cuts that minimise live FpExt count near each geometric target."""
    span = body_end - body_start
    chunk = span // n_funcs
    def_lines = sorted(info['def_line'] for info in table.values())
    def_set = set(def_lines)
    cuts = []
    prev = body_start
    for k in range(1, n_funcs):
        target = body_start + k * chunk
        lo, hi = max(prev + 1, target - window), min(body_end - 1, target + window)
        best = None
        for L in range(lo, hi + 1):
            if L not in def_set:
                continue
            n_live = sum(1 for info in table.values()
                         if info['type'] == 'FpExt' and info['def_line'] < L and info['last_use_line'] >= L)
            score = (n_live, abs(L - target))
            if best is None or score < best[0]:
                best = (score, L)
        cuts.append(best[1] if best else target)
        prev = cuts[-1]
    return cuts


def rewrite_args_and_xrefs(line, name_map):
    """Apply two rewrites: args[N] -> arg<idx> per ARG_MAP; xN -> fargK for crossing FpExt."""
    # Rewrite args[K] indexing
    def args_sub(m):
        k = int(m.group(1))
        return ARG_MAP.get(k, f'args[{k}]')  # fall back to original if unknown
    line = ARGS_RE.sub(args_sub, line)
    # Rewrite FpExt-crossing references (only on RHS — but we apply globally;
    # LHS xN never matches name_map keys because we only put crossings in there).
    if name_map:
        def xref_sub(m):
            xid = int(m.group(1))
            return name_map.get(xid, m.group(0))
        line = XREF_RE.sub(xref_sub, line)
    return line


def compute_closure(table, region_xids):
    """Return all transitive deps of region_xids (i.e., everything they reference)."""
    needed = set()
    work = list(region_xids)
    while work:
        x = work.pop()
        if x in needed:
            continue
        needed.add(x)
        info = table.get(x)
        if not info:
            continue
        for d in info['deps']:
            if d not in needed:
                work.append(d)
    return needed


def emit_subfn(buf, region_idx, region_lo, region_hi, lines, table, prologue_lines,
               num_funcs, fpext_imports, fpext_exports):
    """Emit recursion_v2_<region_idx>.

    region_lo, region_hi: body line range for this sub-function (half-open).
    fpext_imports: list of FpExt xids that flow IN (rewritten to farg0..fargN).
    fpext_exports: list of FpExt xids that flow OUT (used by the callee).
    """
    name_map = {xid: f'farg{i}' for i, xid in enumerate(fpext_imports)}
    # Param list
    sig_parts = ['size_t cycle', 'size_t steps', 'FpExt* poly_mix']
    sig_parts.extend(f'Fp* arg{i}' for i in range(NUM_BUFS))
    sig_parts.extend(f'FpExt farg{i}' for i in range(len(fpext_imports)))
    sig = f'__attribute__((noinline)) FpExt recursion_v2_{region_idx}(' + ', '.join(sig_parts) + ')'
    buf.append(sig + ' {\n')
    buf.append('  size_t mask = steps - 1;\n')
    # Prologue constants (cheap; IGC will fold).
    buf.extend(prologue_lines)
    # Find all xids referenced in [region_lo, region_hi).
    referenced = set()
    for li in range(region_lo, region_hi):
        ln = lines[li]
        eq = ln.find('=')
        rhs = ln[eq + 1:] if eq >= 0 else ln
        for m in XREF_RE.finditer(rhs):
            referenced.add(int(m.group(1)))
    # Closure of referenced over deps.
    closure = compute_closure(table, referenced)
    # Defs IN region: keep as-is.
    region_defs = {xid for xid, info in table.items() if region_lo <= info['def_line'] < region_hi}
    # Defs needed from OUTSIDE region (in [body_start, region_lo)): re-emit at top.
    external_needed = (closure - region_defs)
    # Of those, FpExt imports are passed as fargK (don't re-emit them as defs).
    fpext_import_set = set(fpext_imports)
    to_emit_external = external_needed - fpext_import_set
    # Order by def_line.
    to_emit_external_sorted = sorted(
        (xid for xid in to_emit_external if xid in table),
        key=lambda x: table[x]['def_line']
    )
    # Re-emit each external def's line (and skip its prior `// loc()` comment to keep it tight).
    for xid in to_emit_external_sorted:
        dl = table[xid]['def_line']
        buf.append(rewrite_args_and_xrefs(lines[dl], name_map))
    # Now emit the region's own body, applying rewrites.
    for li in range(region_lo, region_hi):
        ln = lines[li]
        # Skip if this is a def line for an external (already emitted above) — but
        # since region_lo <= def_line < region_hi is required for region_defs, this can't happen.
        buf.append(rewrite_args_and_xrefs(ln, name_map))
    # Emit chain call or return.
    if region_idx > 0:
        # fpext_exports here is the imports list of the NEXT sub-fn (K-1) — pass-through aware.
        # For each FpExt id in callee_imports: it's either defined in our region (region_defs)
        # → pass `xN` (original name) OR an incoming import → pass `fargI` (the fargI we received).
        callee_imports = fpext_exports  # repurposed: see main() — this list is actually callee imports
        names = []
        for xid in callee_imports:
            if xid in region_defs:
                names.append(f'x{xid}')
            elif xid in name_map:
                names.append(name_map[xid])
            else:
                names.append(f'/* MISSING x{xid} */')
        fwd = ', '.join(names)
        bufs = ', '.join(f'arg{i}' for i in range(NUM_BUFS))
        call = f'  return recursion_v2_{region_idx - 1}(cycle, steps, poly_mix, {bufs}'
        if fwd:
            call += f', {fwd}'
        call += ');\n'
        buf.append(call)
    else:
        # Tail: the very last FpExt assignment is the return.
        last_fpext = max(
            (xid for xid, info in table.items() if info['type'] == 'FpExt' and info['def_line'] < region_hi),
            key=lambda x: table[x]['def_line']
        )
        buf.append(f'  return x{last_fpext};\n')
    buf.append('}\n\n')


def emit_poly_fp(buf, prologue_lines, head_idx):
    buf.append('FpExt poly_fp(size_t cycle, size_t steps, FpExt* poly_mix, Fp** args) {\n')
    # Constants from prologue (kept here for parity with the original; IGC will fold).
    buf.extend(prologue_lines)
    buf.append('\n')
    # args[0]=code, args[2]=data, args[3]=mix, args[4]=accum
    buf.append(f'  return recursion_v2_{head_idx}(cycle, steps, poly_mix, '
               '/*code=*/args[0], /*out=*/args[1], /*data=*/args[2], /*mix=*/args[3], /*accum=*/args[4]);\n')
    buf.append('}\n\n')


def emit_forward_decls(buf, num_funcs, fpext_imports_per_region):
    """Per-file forward decls for all recursion_v2_K + poly_fp."""
    for region_idx in range(num_funcs - 1, -1, -1):
        n_in = len(fpext_imports_per_region[region_idx])
        parts = ['size_t cycle', 'size_t steps', 'FpExt* poly_mix']
        parts.extend(f'Fp* arg{i}' for i in range(NUM_BUFS))
        parts.extend(f'FpExt farg{i}' for i in range(n_in))
        buf.append(f'FpExt recursion_v2_{region_idx}(' + ', '.join(parts) + ');\n')
    buf.append('FpExt poly_fp(size_t cycle, size_t steps, FpExt* poly_mix, Fp** args);\n\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('in_path')
    ap.add_argument('out_dir')
    ap.add_argument('--n', type=int, default=10)
    ap.add_argument('--num-files', type=int, default=2)
    ap.add_argument('--dry-run', action='store_true')
    args = ap.parse_args()

    parsed = parse_file(args.in_path)
    lines = parsed['lines']
    body_start = parsed['body_start']
    body_end = parsed['body_end']
    prologue_lines = lines[parsed['header_end']:parsed['prologue_end']]
    print(f'[split_poly_fp] body lines {body_start}..{body_end} ({body_end-body_start} lines)', file=sys.stderr)

    table = build_ssa_table(lines, body_start, body_end)
    print(f'[split_poly_fp] SSA defs: {len(table)} '
          f'(FpExt={sum(1 for i in table.values() if i["type"]=="FpExt")})',
          file=sys.stderr)

    cuts = pick_cuts(table, body_start, body_end, args.n)
    # Region ranges: regions in source order are 0..N-1 where source-order S maps to region_idx N-1-S
    # source-order S: [region_los[S], region_los[S+1])
    region_los = [body_start] + cuts + [body_end]
    print(f'[split_poly_fp] cuts:', file=sys.stderr)
    for i, c in enumerate(cuts):
        print(f'  cut[{i}] @ line {c}', file=sys.stderr)

    # For each region (source-order S, region_idx = N-1-S):
    # - region_lo = region_los[S], region_hi = region_los[S+1]
    # - fpext_imports = FpExt xids def<region_lo, last_use>=region_lo (sorted by def_line)
    # - fpext_exports = FpExt xids def in [region_lo, region_hi), last_use >= region_hi (sorted by def_line)
    # source order S=0 maps to region_idx = N-1 (head, called from poly_fp)
    # source order S=N-1 maps to region_idx = 0 (tail, returns final)
    fpext_imports = [None] * args.n
    fpext_exports = [None] * args.n
    for s in range(args.n):
        region_idx = args.n - 1 - s
        lo = region_los[s]
        hi = region_los[s + 1]
        imports = sorted(
            (xid for xid, info in table.items()
             if info['type'] == 'FpExt' and info['def_line'] < lo and info['last_use_line'] >= lo),
            key=lambda x: table[x]['def_line']
        )
        exports = sorted(
            (xid for xid, info in table.items()
             if info['type'] == 'FpExt' and lo <= info['def_line'] < hi and info['last_use_line'] >= hi),
            key=lambda x: table[x]['def_line']
        )
        fpext_imports[region_idx] = imports
        fpext_exports[region_idx] = exports
        print(f'  region S={s} (rec_v2_{region_idx}) lines [{lo}..{hi}) imports={len(imports)} exports={len(exports)}',
              file=sys.stderr)

    if args.dry_run:
        return

    os.makedirs(args.out_dir, exist_ok=True)

    # Distribute regions across files. File 0 gets the highest-numbered (head) sub-fns.
    region_idxs = list(range(args.n - 1, -1, -1))  # head to tail
    per_file = [args.n // args.num_files] * args.num_files
    for i in range(args.n % args.num_files):
        per_file[i] += 1

    cursor = 0
    for f_idx in range(args.num_files):
        buf = [HEADER_TEMPLATE]
        emit_forward_decls(buf, args.n, fpext_imports)
        my_regions = region_idxs[cursor:cursor + per_file[f_idx]]
        cursor += per_file[f_idx]
        for region_idx in my_regions:
            s = args.n - 1 - region_idx
            lo = region_los[s]
            hi = region_los[s + 1]
            # Sub-fn K calls K-1 with K-1's imports.  For the tail (region_idx=0)
            # there's no callee, so pass empty list.
            callee_imports = fpext_imports[region_idx - 1] if region_idx > 0 else []
            emit_subfn(buf, region_idx, lo, hi, lines, table, prologue_lines,
                       args.n, fpext_imports[region_idx], callee_imports)
        # Last file gets poly_fp entry.
        if f_idx == args.num_files - 1:
            emit_poly_fp(buf, prologue_lines, args.n - 1)
        buf.append(NS_CLOSE)
        out_path = os.path.join(args.out_dir, f'rust_poly_fp_{f_idx}.cpp')
        text = ''.join(buf)
        with open(out_path, 'w') as f:
            f.write(text)
        print(f'[split_poly_fp] wrote {out_path} ({text.count(chr(10))} lines)', file=sys.stderr)


if __name__ == '__main__':
    main()
